### ISSUE TITLE
Support importing/exporting .swc files directly to AWS s3

### ISSUE THREAD

**Issue by carshadi** [JaneliaSciComp/hortacloud#2]
## Proposal

Something that would be super useful is the ability to import and export `.swc` files directly from s3, using the top gear menu in the Horta Control Center, e.g., "Import SWC Files as One Neuron...". This would avoid having to go through the "Temporary Files" folder as a middle-man.

## Suggest implementation 

I would be happy to contribute this if someone could point me to the relevant classes and give a general outline of what needs to be accounted for / tested

**Comment by krokicki** [comment]
Hi, @carshadi, it's nice to hear from you!

I've moved this issue to the hortacloud repo, so we can manage all the related issues together. 

This is a great idea, and I think there are many potential implementations we can consider. It also dovetails with S3 support that we want to add for Horta image loading. I'll follow up about it once we've discussed more internally, but if you have any specific requirements or implementation ideas, please let us know. Your offer to help sounds great, we just need to rough out how this will integrate with other features. 

Thanks,
Konrad

**Comment by krokicki** [comment]
@carshadi, since Cristian implemented the ability to import a ZIP file full of SWCs, do you consider this feature still necessary?

**Comment by carshadi** [comment]
That should work for me, I'm OK with closing this.
