### ISSUE TITLE
 Brain Tile doesn't load correctly

### ISSUE THREAD

**Issue by C-Alonso-Martinez** [JaneliaSciComp/hortacloud#3]
I am running into some problems with the workstation that don't let me correctly use the Horta 3D viewer. The problem is that I always end up with a black screen and not being able to see the brain. The most common problem is that I am correctly following an axon, with lot of zoom in, and suddenly there are no more brain squares loaded and I just can see the traced neuron. I waited (5-10 minutes), I tried zooming in and out and moving the brain, but nothing changes. All the other interactive things of the workstation seem to work, but the brain doesn't load. All this time, I see the loading bar, but even if I wait for 15-20 minutes nothing changes, so I asume that something has freezed. 

At some time a window pops up saying "Brain Raw Data Error":
Error loading brain specimen:java.lang.IllegalStateException: HTTP status 504 (not OK) from url https://ip-10-0-0-80.us-west-2.compute.internal/SCSW/JACS2SyncServices/v2/mouselight/samples/3087594671233310722/volumen_info

If I close the session and reload everything, then it works fine at first, until I run into the same problems.The same thing happens with different neurons (I tried it with AA0345 and AA0346). I am running them on the Tile Microscope Sample that I created, of the 2017-09-19 brain.

**Comment by cgoina** [comment]
Could you please give us the sample path from the workstation. To do that select the sample in the workstation and look at the "Data Inspector". From the "Data Inspector" get the value(s) for "KTX Filepath" and/or "Octree Filepath" and put them in the ticket. Either value is enough, we don't really need both values

**Comment by C-Alonso-Martinez** [comment]
Hello,

Here are both filepaths just in case you need them.

KTX Filepath: /janelia-mouselight-imagery/images/2017-09-19/ktx
Octree Filepath: /janelia-mouselight-imagery/images/2017-09-19

Do you want me to also copy them on GitHub? Thanks in advance for the help.

Carmen

**Comment by cgoina** [comment]
@C-Alonso-Martinez are you still experiencing problem?
